### ISSUE TITLE
Add 100% unit test coverage

### ISSUE THREAD

**Issue by MadaraUchiha-314** [intuit/text-provider#17]
- Integrate with jest and enzyme
- Make the code 100% unit tested

**Comment by rachanamamillapalli** [comment]
Hi @MadaraUchiha-314, I would like to work on this!

**Comment by MadaraUchiha-314** [comment]
@rachanamamillapalli Assigned

**Comment by rachanamamillapalli** [comment]
@MadaraUchiha-314 Could you review the PR linked to this issue?
