### ISSUE TITLE
Upgrade to latest React 16.9.0

### ISSUE THREAD

**Issue by MadaraUchiha-314** [intuit/text-provider#2]
The current context API being used is from an older version of React when context was still experimental in react.

Look at this for the new implementation : https://reactjs.org/docs/context.html

Tasks :
- Will have to decide whether this breaks backward compatibility. If yes, we will have to do a minor/major version release and then update the code accordingly.

**Comment by Konoha-14** [comment]
Will take this up.

**Comment by MadaraUchiha-314** [comment]
Assigned!
