### ISSUE TITLE
Integrate with semantic-versioning for automatic releases

### ISSUE THREAD

**Issue by MadaraUchiha-314** [intuit/text-provider#70]

**Comment by rachanamamillapalli** [comment]
@MadaraUchiha-314 Can we integrate [auto](https://github.com/intuit/auto) for this? If yes, I can take this up.

**Comment by MadaraUchiha-314** [comment]
@rachanamamillapalli I prefer semantic releases vs auto label based releases.

**Comment by skodamarthi** [comment]
@MadaraUchiha-314 I tried using semantic-release for this. Please let me know your thoughts.

**Comment by MadaraUchiha-314** [comment]
@skodamarthi Yes. This is what I was look for. Assigning the issue to you.
