### ISSUE TITLE
Added the ability to provide values in getTextForKey

### ISSUE THREAD

**Issue by MadaraUchiha-314** [intuit/text-provider#78]
The `FormattedMessage` component has an ability to provide values to replace placeholders in the text with actual values. The same functionality needs to be present in `getTextForKey` function.

**Comment by RitikPandey1** [comment]
@MadaraUchiha-314  I would like to work on this ,can i take this issue ?

**Comment by MadaraUchiha-314** [comment]
@RitikPandey1 Assigned.

**Comment by skaushik16** [comment]
@MadaraUchiha-314  Can more than one person contribute for this?

**Comment by pranvatsa** [comment]
Hi @MadaraUchiha-314  , Can i look into this ?

**Comment by samrae7** [comment]
@RitikPandey1 are you working on this? If not I'd like to take a look

**Comment by samrae7** [comment]
retracting my offer above because I didn't hear back and have got busy now
