### ISSUE TITLE
Add React Hooks as a way to consume the text directly from the context

### ISSUE THREAD

**Issue by MadaraUchiha-314** [intuit/text-provider#80]
Currently the `globalText` is stored using the React.Context. This is provided as an HOC using `withTextProvider`, but with the incoming of React Hooks, this can be exposed by creating a custom hook for `text-provider`

**Comment by cjharkins** [comment]
I'll take this

**Comment by MadaraUchiha-314** [comment]
@cjharkins Assigned.

**Comment by oscargrp** [comment]
Hey @cjharkins let me know if you need any help on this one, I'd be happy to help 👍

**Comment by connerdodge** [comment]
I didn't see any progress on this issue, so I raised a PR to address it.

**Comment by cjharkins** [comment]
Hey sorry everyone, got overloaded, I'll unassign myself. My apologies.

**Comment by pramodrhegde** [comment]
@MadaraUchiha-314 I would like to take this up, could you please assign this to me?

**Comment by alihamuh** [comment]
Any progress?
I want to work on this one.

**Comment by MadaraUchiha-314** [comment]
@alihamuh There is already a PR raised for this.

**Comment by Anmollenka** [comment]
Can I work on this issue?

**Comment by skodamarthi** [comment]
@MadaraUchiha-314 Can I work on this as part of hacktoberfest?
