### ISSUE TITLE
Add an example project using online JS environments.

### ISSUE THREAD

**Issue by MadaraUchiha-314** [intuit/text-provider#89]
Use something like:
- https://codesandbox.io/
- https://codepen.io/

to provide working examples of text-provider.

**Comment by KevinAmarsha** [comment]
@MadaraUchiha-314  I can work on this.

**Comment by SahanAmarsha** [comment]
@MadaraUchiha-314 
I can work on this.

**Comment by nsinghal12** [comment]
Hi @MadaraUchiha-314 - I have created the example project at https://codesandbox.io/s/inspiring-vaughan-t4f15. Please review and let me know your feedback.
